name: Release

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to DockerHub
      uses: gythialy/Publish-Docker-Github-Action@master
      with:
        name: goreng/publish-docker-github-action
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Publish to GitHub Packages
      uses: gythialy/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/gythialy/publish-docker-github-action/publish-docker-github-action
        username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        registry: docker.pkg.github.com

